version: 0.2

phases:
    install:
        commands:
            - pip3 install -q awscli --upgrade --user
            - pip3 install boto3
            - yum -q install -y jq
            - wget -qO /tmp/sonar-scanner.zip "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip"
            - unzip -q /tmp/sonar-scanner.zip -d /tmp
    pre_build:
        commands:
            - echo Start code scan...
            - ./../../../../../../../tmp/sonar-scanner-4.7.0.2747-linux/bin/sonar-scanner -Dsonar.projectKey=DiscussHub -Dsonar.sources=. -Dsonar.host.url=http://<url>:9000 -Dsonar.login=sqp_7ff2fe4e83d92988a51a754a751b72448cbc21a1
            - sleep 7
            - "curl -s -u sqp_7ff2fe4e83d92988a51a754a751b72448cbc21a1: http://<url>:9000/api/qualitygates/project_status?projectKey=DiscussHub> /tmp/result.json"
            - if [ $(jq -r '.projectStatus.status' /tmp/result.json) = ERROR ] ; then CODEBUILD_BUILD_SUCCEEDING=0 ; fi
            - echo Code scan completed on `date`
            - if [ "$CODEBUILD_BUILD_SUCCEEDING" -eq 0 ]; then exit 1; fi
eb_codebuild_settings:
  aws_beanstalk_application:
    name: "X22228811"
  aws_beanstalk_environment:
    name: "X22228811-env"